[package]
name = "rust-twig-tools"
version = "0.1.0"
authors = ["Malte Janz <malte.janz@yahoo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true # does increase runtime performance for longer build times
#only for profiling! remove for release
#debug = 1

[dependencies]
twig = { path="libs/twig" }
clap = "~3.0.0-beta.2"
tokio = { version = "^0.3.5", features = ["rt-multi-thread", "fs", "io-util", "stream", "macros", "sync"] }
colored = "~2.0.0"
walkdir = "^2.3.1"
