[package]
name = "rust-twig-tools"
version = "0.1.0"
authors = ["Malte Janz <malte.janz@yahoo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twig = { path="libs/twig" }
clap = "3.0.0-beta.2"
async-std = "1.6.5"