[package]
name = "ludtwig"
version = "0.1.0"
authors = ["Malte Janz <malte.janz@yahoo.de>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true # does increase runtime performance for longer build times
opt-level = 3 # maximum of code optimization (use "s" for optimized binary size)
codegen-units = 1 # do not compile crates in parallel to allow for further optimization
#only for profiling! remove for release
#debug = 1

[dependencies]
twig = { path="libs/twig" }
clap = "~3.0.0-beta.2"
tokio = { version = "~1.1.0", features = ["rt-multi-thread", "sync", "fs", "io-util", "macros"] }
ansi_term = "~0.12.1"
walkdir = "~2.3.1"
async-trait = "0.1.42"
