# Ludtwig configuration

# To override any of these values with environment variables use the following format:
# LUDTWIG_FORMAT__INDENTATION_COUNT=1

[general]
active-rules = [
    "whitespace-between-line-breaks",
    "line-ending",
    "indentation",
    "twig-block-line-breaks",
    "twig-block-name-snake-case",
    "html-attribute-name-kebab-case",
]

[format]
# How should the line endings look like? ["unix_LF", "windows_CRLF"]
# unix_LF is a single '\n' character
# windows_CRLF are the characters '\r\n'
# checked by the 'line-ending' rule
line-ending = "unix_LF"

# Which character should be used for indentation ["space", "tab"]
# checked by the 'indentation' rule
indentation-mode = "space"
# How many times should this character be printed for one indentation [0-255]
# checked by the 'indentation' rule
indentation-count = 4
# Should the children of twig blocks be indented? [true, false]
# checked by the 'indentation' rule
indent-children-of-blocks = true

# Should twig blocks have empty lines around them? [true, false]
# checked by the 'twig-block-line-breaks' rule
linebreaks-around-blocks = true
