on:
  workflow_dispatch:
  # ToDo: Add on tag push

name: Publish

jobs:
  publish_crate:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install latest stable Rust version
        uses: dtolnay/rust-toolchain@stable

      - name: Publish ludtwig-parser
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: cargo publish --token ${CRATES_TOKEN} -p ludtwig-parser --dry-run

      - name: Publish ludtwig
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: cargo publish --token ${CRATES_TOKEN} -p ludtwig --dry-run

  publish_docker:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: "maltejanz/ludtwig"
    steps:
      - uses: actions/checkout@v4

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.ref_type == 'tag' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
